version: 2

jobs:
  jvm8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/mojang4j

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
        paths:
          - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test


workflows:
  version: 2
  all:
    jobs:
      - jvm8